foreach name in lvl imp score {
label variable skill1_`name'	"Reading Comprehension	"
label variable skill2_`name'	"Active Listening	"
label variable skill3_`name'	"Writing	"
label variable skill4_`name'	"Speaking	"
label variable skill5_`name'	"Mathematics	"
label variable skill6_`name'	"Science	"
label variable skill7_`name'	"Critical Thinking	"
label variable skill8_`name'	"Active Learning	"
label variable skill9_`name'	"Learning Strategies	"
label variable skill10_`name'	"Monitoring	"
label variable skill11_`name'	"Social Perceptiveness	"
label variable skill12_`name'	"Coordination	"
label variable skill13_`name'	"Persuasion	"
label variable skill14_`name'	"Negotiation	"
label variable skill15_`name'	"Instructing	"
label variable skill16_`name'	"Service Orientation	"
label variable skill17_`name'	"Complex Problem Solving	"
label variable skill18_`name'	"Operations Analysis	"
label variable skill19_`name'	"Technology Design	"
label variable skill20_`name'	"Equipment Selection	"
label variable skill21_`name'	"Installation	"
label variable skill22_`name'	"Programming	"
label variable skill23_`name'	"Operation Monitoring	"
label variable skill24_`name'	"Operation and Control	"
label variable skill25_`name'	"Equipment Maintenance	"
label variable skill26_`name'	"Troubleshooting	"
label variable skill27_`name'	"Repairing	"
label variable skill28_`name'	"Quality Control Analysis	"
label variable skill29_`name'	"Judgment and Decision Making	"
label variable skill30_`name'	"Systems Analysis	"
label variable skill31_`name'	"Systems Evaluation	"
label variable skill32_`name'	"Time Management	"
label variable skill33_`name'	"Management of Financial Resources	"
label variable skill34_`name'	"Management of Material Resources	"
label variable skill35_`name'	"Management of Personnel Resources	"
}
