foreach name in lvl imp score {
label variable abil1_`name'	"Oral Comprehension		"
label variable abil2_`name'	"Written Comprehension		"
label variable abil3_`name'	"Oral Expression		"
label variable abil4_`name'	"Written Expression		"
label variable abil5_`name'	"Fluency of Ideas		"
label variable abil6_`name'	"Originality		"
label variable abil7_`name'	"Problem Sensitivity		"
label variable abil8_`name'	"Deductive Reasoning		"
label variable abil9_`name'	"Inductive Reasoning		"
label variable abil10_`name'	"Information Ordering		"
label variable abil11_`name'	"Category Flexibility		"
label variable abil12_`name'	"Mathematical Reasoning		"
label variable abil13_`name'	"Number Facility		"
label variable abil14_`name'	"Memorization		"
label variable abil15_`name'	"Speed of Closure		"
label variable abil16_`name'	"Flexibility of Closure		"
label variable abil17_`name'	"Perceptual Speed		"
label variable abil18_`name'	"Spatial Orientation		"
label variable abil19_`name'	"Visualization		"
label variable abil20_`name'	"Selective Attention		"
label variable abil21_`name'	"Time Sharing		"
label variable abil22_`name'	"Arm-Hand Steadiness		"
label variable abil23_`name'	"Manual Dexterity		"
label variable abil24_`name'	"Finger Dexterity		"
label variable abil25_`name'	"Control Precision		"
label variable abil26_`name'	"Multilimb Coordination		"
label variable abil27_`name'	"Response Orientation		"
label variable abil28_`name'	"Rate Control		"
label variable abil29_`name'	"Reaction Time		"
label variable abil30_`name'	"Wrist-Finger Speed		"
label variable abil31_`name'	"Speed of Limb Movement		"
label variable abil32_`name'	"Static Strength		"
label variable abil33_`name'	"Explosive Strength		"
label variable abil34_`name'	"Dynamic Strength		"
label variable abil35_`name'	"Trunk Strength		"
label variable abil36_`name'	"Stamina		"
label variable abil37_`name'	"Extent Flexibility		"
label variable abil38_`name'	"Dynamic Flexibility		"
label variable abil39_`name'	"Gross Body Coordination		"
label variable abil40_`name'	"Gross Body Equilibrium		"
label variable abil41_`name'	"Near Vision		"
label variable abil42_`name'	"Far Vision		"
label variable abil43_`name'	"Visual Color Discrimination		"
label variable abil44_`name'	"Night Vision		"
label variable abil45_`name'	"Peripheral Vision		"
label variable abil46_`name'	"Depth Perception		"
label variable abil47_`name'	"Glare Sensitivity		"
label variable abil48_`name'	"Hearing Sensitivity		"
label variable abil49_`name'	"Auditory Attention		"
label variable abil50_`name'	"Sound Localization		"
label variable abil51_`name'	"Speech Recognition		"
label variable abil52_`name'	"Speech Clarity		"
}
