foreach name in lvl imp score {
label variable knowl1_`name'	"Administration and Management	"
label variable knowl2_`name'	"Clerical	"
label variable knowl3_`name'	"Economics and Accounting	"
label variable knowl4_`name'	"Sales and Marketing	"
label variable knowl5_`name'	"Customer and Personal Service	"
label variable knowl6_`name'	"Personnel and Human Resources	"
label variable knowl7_`name'	"Transportation	"
label variable knowl8_`name'	"Production and Processing	"
label variable knowl9_`name'	"Food Production	"
label variable knowl10_`name'	"Computers and Electronics	"
label variable knowl11_`name'	"Engineering and Technology	"
label variable knowl12_`name'	"Design	"
label variable knowl13_`name'	"Building and Construction	"
label variable knowl14_`name'	"Mechanical	"
label variable knowl15_`name'	"Mathematics	"
label variable knowl16_`name'	"Physics	"
label variable knowl17_`name'	"Chemistry	"
label variable knowl18_`name'	"Biology	"
label variable knowl19_`name'	"Psychology	"
label variable knowl20_`name'	"Sociology and Anthropology	"
label variable knowl21_`name'	"Geography	"
label variable knowl22_`name'	"Medicine and Dentistry	"
label variable knowl23_`name'	"Therapy and Counseling	"
label variable knowl24_`name'	"Education and Training	"
label variable knowl25_`name'	"English Language	"
label variable knowl26_`name'	"Foreign Language	"
label variable knowl27_`name'	"Fine Arts	"
label variable knowl28_`name'	"History and Archeology	"
label variable knowl29_`name'	"Philosophy and Theology	"
label variable knowl30_`name'	"Public Safety and Security	"
label variable knowl31_`name'	"Law and Government	"
label variable knowl32_`name'	"Telecommunications	"
label variable knowl33_`name'	"Communications and Media	"
}
